Traceback (most recent call last):
  File "/home/xinyi/quito_ex3/quito_test.py", line 6, in <module>
    quito('/home/xinyi/quito_ex3/as.ini')
  File "/home/xinyi/quito_ex3/quito_gpu.py", line 38, in quito
    _quito_run(con_file)
  File "/home/xinyi/quito_ex3/quito_gpu.py", line 1096, in _quito_run
    _input_coverage(inputID, valid_input, valid_output, num_qubit, outputID, p, module_name, program_folder)
  File "/home/xinyi/anaconda3/envs/quito_gpu/lib/python3.10/site-packages/numba/core/dispatcher.py", line 471, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/home/xinyi/anaconda3/envs/quito_gpu/lib/python3.10/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.UnsupportedError: Failed in object mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (STORE_GLOBAL) found

File "quito_gpu.py", line 223:
def _input_coverage(inputID, valid_input, valid_output, num_qubit, outputID, p, module_name, program_folder):
    <source elided>
                end = time.time()
                T2 += end-start
                ^

